version: "3.7"

services:
    mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: mssql-server
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Passwd1234"
            ACCEPT_EULA: "Y"
        volumes:
            - mssql-data:/var/opt/mssql

volumes:
    mssql-data:
        driver: local